name: Release
on:
  push:
    branches:
      - master
      - next
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          version: 12.x

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Publish to npm
        run: yarn run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
